export const CatalogErrorCodes = {
  CATEGORY_NOT_FOUND: 'CATALOG.CATEGORY_NOT_FOUND',
  CATEGORY_HAS_ACTIVE_PRODUCTS: 'CATALOG.CATEGORY_HAS_ACTIVE_PRODUCTS',
  CATEGORY_FORBIDDEN: 'CATALOG.CATEGORY_FORBIDDEN',
  PRODUCT_NOT_FOUND: 'CATALOG.PRODUCT_NOT_FOUND',
  PRODUCT_FORBIDDEN: 'CATALOG.PRODUCT_FORBIDDEN',
  PRODUCT_HAS_ACTIVE_ORDERS: 'CATALOG.PRODUCT_HAS_ACTIVE_ORDERS',
  TENANT_NOT_FOUND: 'CATALOG.TENANT_NOT_FOUND',
  REORDER_FORBIDDEN: 'CATALOG.REORDER_FORBIDDEN',
} as const;
