export const OrderErrorCodes = {
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_FORBIDDEN: 'ORDER_FORBIDDEN',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  DELIVERY_NOT_ENABLED: 'DELIVERY_NOT_ENABLED',
  TAKEAWAY_NOT_ENABLED: 'TAKEAWAY_NOT_ENABLED',
  IN_STORE_NOT_ENABLED: 'IN_STORE_NOT_ENABLED',
  PAYMENT_METHOD_NOT_ENABLED: 'PAYMENT_METHOD_NOT_ENABLED',
  BELOW_MINIMUM_ORDER: 'BELOW_MINIMUM_ORDER',
  TENANT_SETTINGS_NOT_FOUND: 'TENANT_SETTINGS_NOT_FOUND',
} as const;
