export enum FeatureCode {
  REMOVE_BRANDING = 'REMOVE_BRANDING',
  CUSTOM_DOMAIN = 'CUSTOM_DOMAIN',
  ANALYTICS = 'ANALYTICS',
  PRIORITY_SUPPORT = 'PRIORITY_SUPPORT',
  MULTI_BRANCH = 'MULTI_BRANCH',
  API_ACCESS = 'API_ACCESS',
  AI_ASSISTANT = 'AI_ASSISTANT',
}
